# Generated by Django 3.1.1 on 2020-09-24 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_paybills'),
    ]

    operations = [
        migrations.AddField(
            model_name='moneysend',
            name='amount',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AddField(
            model_name='moneysend',
            name='receiver',
            field=models.CharField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='moneysend',
            name='sender',
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paybills',
            name='amount',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AddField(
            model_name='paybills',
            name='receiver',
            field=models.CharField(default=2, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paybills',
            name='sender',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
