# Generated by Django 3.1.1 on 2020-09-24 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200924_0032'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=255)),
                ('receivernumber', models.CharField(max_length=254)),
                ('amount', models.CharField(default=0, max_length=255)),
                ('description', models.CharField(default='Payment Processed on', max_length=255)),
                ('paymenton', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameField(
            model_name='paybills',
            old_name='receiver',
            new_name='category',
        ),
        migrations.AddField(
            model_name='paybills',
            name='meter',
            field=models.CharField(default='', max_length=255),
        ),
    ]
